# Spring Application Name
spring.application.name=Caremate

# Datasource Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Caremate?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=@Arpita2209ghabak

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Multipart Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Server Port
server.port=8888

# Swagger/OpenAPI Configuration
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# JWT Security Settings
application.security.jwt.secret-key=4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
application.security.jwt.access-token-expiration=86400000
application.security.jwt.refresh-token-expiration=604800000

# WhatsBot API Token
whatsbot.api.token=f2926fca-5773-496e-8921-2daf3718ace4
